%YAML:1.0
---

# 标定部分

boardSize_h: 7 # 棋盘参数
boardSize_w: 9
squareSize: 1.5 
img_count: 60 # 六十张图片
sample_period: 20 # 20 帧每张图片
calib_yaml_path: "../config/camera_paramets.yaml" # 相机内参

# 控制相机亮度
cam_gain: 15.2
cam_exptime: 12000

framerate: 120 # 帧率

# 可视化与调试模式
imshow_en: 1
debug_info: 1

# 小装甲板和大装甲板信息 
armor_small_h: 50
armor_small_w: 135
armor_large_h: 50
armor_large_w: 200